name: Minha_Gazoza
description: Somos um grupo de estudantes e estamos no último ano da escola, iniciamos o curso em 2020 na ETEC Antônio Furlan. No início de 2022, entramos com o projeto de TCC “Gestão de combustível”. Com esse projeto, temos o objetivo de ajudar a fazer cálculos mais rápidos e a controlar os gastos de\n\n consumo do usuário.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  charts_flutter: ^0.12.0

  sqflite: ^2.0.2+1
  path: ^1.8.0
  flutter_launcher_icons: ^0.11.0
 
  
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0




flutter:


  uses-material-design: true

  assets:

  - assets/images/LogoApp.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/LogoApp.png"
  min_sdk_android: 21 